### ISSUE TITLE
Question about "rot_rep_idx" and "pos_rep_idx"

### ISSUE THREAD

**Issue by wolegequwangge** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#19]
Thank you very much for your work.
I would like to know what "rot_rep_idx"  and "pos_rep_idx" mean (in src/Net/StyleVAENet.py, line 118 and src/Net/TransitionPhaseNet.py, line 192) . 
I have observed that they are related to the skeleton. If the skeleton is changed, do they need to be reassigned?

**Comment by yuyujunjun** [comment]
Thank you. Our method uses the rotation representation only to determine the joint's attribute if the joint is in rot_rep_idx. For example, joint 1 is in rot_rep_idx, which connects the right leg and hip, and the hip orientation determines its position. We cannot arbitrarily change the position of joint 1 because it also changes the orientation of the hip joint, which is undesirable. 

If the skeleton changes, I recommend you to reassign these two lists based on the principle below. 

First, we use position representation for end-effectors to increase their position accuracy, because their position accuracy is crucial for avoiding foot-skating artifacts. It's also the main reason for using position representation.

Second, we use rotation representation for spine joints for stable estimation. Rotation is sufficient for spine joints because their positions do not change significantly. Besides, the network might introduce position errors for spine joints as we don't apply loss explicitly for them.

**Comment by wolegequwangge** [comment]
Okay, thank you very much. I got it, and I will reply to you after trying it out.
