### ISSUE TITLE
About generalization of model

### ISSUE THREAD

**Issue by henrycjh** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#7]
The models are trained based on dataset that has mostly dynamic motions. I guess the models will not generalize well if I want to predict motions that are almost static ?

**Comment by yuyujunjun** [comment]
Actually, 100Style has static motion sequences. Additionally, predicting static motion is simpler for in-between motion tasks. This implies that even if we were to remove the static sequences from the training set, generating static motion wouldn't be an issue. On the other hand, maintaining dynamic motion is quite complex, which is why previous methods have struggled to generate it.

Take a look at the video below for an example (static motion occurs at 6:35 and 7:15)
[video](http://www.cad.zju.edu.cn/home/jin/sig20232/demo.mp4)

**Comment by henrycjh** [comment]
Thanks for your patiently reply !
